image: docker:stable
services:
  - name: docker:stable-dind
    command: ["--mtu=1450"]

stages:
  - test
  - publish

variables:
  DOCKER_REGISTRY: "ryama0"
  DOCKER_HOST: "tcp://localhost:2375"

.test_job_template: &test_job
  stage: test
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:test ./$TARGET_DIR
  tags:
    - runner=kubernetes
    - arch=armhf
  except:
    - master

.publish_job_template: &publish_job
  stage: publish
  before_script:
    - docker login -u $USERNAME -p $PASSWORD
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest ./$TARGET_DIR
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
  tags:
    - runner=kubernetes
    - arch=armhf
  only:
    - master
  retry:
    max: 2
    when:
      - script_failure

.prometheus_job_template: &prometheus_job
  variables:
    DOCKER_IMAGE_NAME: "prometheus-armhf"
    TARGET_DIR: "prometheus"

.alertmanager_job_template: &alertmanager_job
  variables:
    DOCKER_IMAGE_NAME: "alertmanager-armhf"
    TARGET_DIR: "alertmanager"

.node_exporter_job_template: &node_exporter_job
  variables:
    DOCKER_IMAGE_NAME: "node_exporter-armhf"
    TARGET_DIR: "node_exporter"

test_prometheus:
  <<: *test_job
  <<: *prometheus_job

publish_prometheus:
  <<: *publish_job
  <<: *prometheus_job

test_alertmanager:
  <<: *test_job
  <<: *alertmanager_job

publish_alertmanager:
  <<: *publish_job
  <<: *alertmanager_job

test_node_exporter:
  <<: *test_job
  <<: *node_exporter_job

publish_node_exporter:
  <<: *publish_job
  <<: *node_exporter_job
