image: docker:stable
services:
  - name: docker:stable-dind
    command: ["--mtu=1450"]

stages:
  - test
  - publish

variables:
  DOCKER_REGISTRY: "ryama0"
  DOCKER_HOST: "tcp://localhost:2375"
  ARCH: armv7
  SOURCE: debian:stretch

.test_job_template: &test_job
  stage: test
  script:
    - docker build --build-arg SOURCE=${SOURCE} --build-arg VERSION=${VERSION} --build-arg ARCH=${ARCH} -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:test ./$TARGET_DIR
  tags:
    - runner=kubernetes
    - arch=armhf
  only:
    - merge_requests

.publish_job_template: &publish_job
  stage: publish
  before_script:
    - docker login -u $USERNAME -p $PASSWORD
  script:
    - docker build --build-arg SOURCE=${SOURCE} --build-arg VERSION=${VERSION} --build-arg ARCH=${ARCH} -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$VERSION ./$TARGET_DIR
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$VERSION
  tags:
    - runner=kubernetes
    - arch=armhf
  only:
    - master
  retry:
    max: 2
    when:
      - script_failure

.prometheus_job_template: &prometheus_job
  variables:
    DOCKER_IMAGE_NAME: "prometheus-armhf"
    TARGET_DIR: "prometheus"
    VERSION: 2.8.0

.alertmanager_job_template: &alertmanager_job
  variables:
    DOCKER_IMAGE_NAME: "alertmanager-armhf"
    TARGET_DIR: "alertmanager"
    VERSION: 0.16.1

.node_exporter_job_template: &node_exporter_job
  variables:
    DOCKER_IMAGE_NAME: "node_exporter-armhf"
    TARGET_DIR: "node_exporter"
    VERSION: 0.17.0

test_prometheus:
  <<: *test_job
  <<: *prometheus_job

publish_prometheus:
  <<: *publish_job
  <<: *prometheus_job

test_alertmanager:
  <<: *test_job
  <<: *alertmanager_job

publish_alertmanager:
  <<: *publish_job
  <<: *alertmanager_job

test_node_exporter:
  <<: *test_job
  <<: *node_exporter_job

publish_node_exporter:
  <<: *publish_job
  <<: *node_exporter_job
